name: firebase_helpers
description: A package that provides various Google Firebase related services
  helpers. Provides helpers to perform queries on firestore, firebase auth etc.
version: 0.5.0
homepage: https://github.com/lohanidamodar/flutter_firebase_helpers
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
